export const localization = {
  cyr: {
    translation: {
      lang: "Тил",
      logout: "Чикиш",
      users: "Фойдаланувчилар",
      objects: "Объектлар",
      map: "Харита",
      settings: "Созламалар",
      error: "Тақиқланган",
      notEntry: "Сизда тизимга киришга ҳуқуқ ёқ",
      goBack: "Ортга қайтиш",
      cadNum: "Кадастр рақами",
      orgName: "Ташкилот номи",
      buildYear: "Қурилиш йили",
      addedBuildCount: "Қўшилган бинолар сони",
      buildCount: "Бинолар сони",
      created: "Қўшди",
      edited: "Ўзгартирди",
      userInfo: "Фойдаланувчи маълумотлари",
      name: "Исм",
      lastName: "Фамилия",
      midName: "Отасининг исми",
      phoneNumber: "Телефон рақами",
      email: "Электрон почта манзили",
      close: "Ёпиш",
      search: "Қидириш",
      createNewUser: "Янги фойдаланувчи яратиш",
      login: "Логин",
      password: "Парол",
      cancel: "Бекор қилиш",
      save: "Сақлаш",
      enter: "Кириш",
      continueEnter: "Давом эттириш учун, киринг",
      buildName: "Бино номи",
      address: "Адрес",
      fullInfo: "Тўлиқ маълумот",
      copied: "Кўчириб олинди!",
      objCadNum: "Объект кадастр рақами",
      objRegion: "Объект жойлашган вилоят",
      objDistrict: "Объект жойлашган туман ёки шаҳар",
      objNeighborhood: "Объект жойлашган маҳалла",
      objStreet: "Объект жойлашган кўча, уй",
      objBuildYear: "Объект қурилган йил",
      objDatePassport: "Объект паспорти тўлдирилган сана",
      objHistorical: "Объектнинг тарихий-маданий аҳамиятга эга эканлиги",
      objBuildCount: "Бино ва иншоотлар сони",
      createUser: "Фойдаланувчи яратиш",
      have: "Эга",
      notHave: "Эга эмас",
      organizations: "Ташкилотлар",
      orgList: "Ташкилотлар рўйхати",
      objCount: "Объектлар сони",
      orgCount: "Ташкилотлар сони",
    },
  },
  uz: {
    translation: {
      lang: "Til",
      logout: "Chiqish",
      users: "Foydalanuvchilar",
      objects: "Obyektlar",
      map: "Xarita",
      settings: "Sozlamalar",
      error: "Taqiqlangan",
      notEntry: "Sizda tizimga kirishga xuquq y'oq",
      goBack: "Ortga qaytish",
      cadNum: "Kadastr raqami",
      orgName: "Tashkilot nomi",
      buildYear: "Qurilish yili",
      addedBuildCount: "Qo'shilgan binolar soni",
      buildCount: "Binolar soni",
      created: "Qo'shdi",
      edited: "O'zgartirdi",
      userInfo: "Foydalanuvchi ma'lumotlari",
      name: "Ism",
      lastName: "Familiya",
      midName: "Otasining ismi",
      phoneNumber: "Telefon raqami",
      email: "Elektron po'chta manzili",
      close: "Yopish",
      search: "Qidirish",
      createNewUser: "Yangi foydalanuvchi yaratish",
      login: "Login",
      password: "Parol",
      cancel: "Bekor qilish",
      save: "Saqlash",
      enter: "Kirish",
      continueEnter: "Davom ettirish uchun, kiring",
      buildName: "Bino nomi",
      address: "Manzil",
      fullInfo: "To'liq ma'lumot",
      copied: "Ko'chirib olindi!",
      objCadNum: "Obyekt kadastr raqami",
      objRegion: "Obyekt joylashgan viloyat",
      objDistrict: "Obyekt joylashgan tuman yoki shahar",
      objNeighborhood: "Obyekt joylashgan mahalla",
      objStreet: "Obyekt joylashgan ko'cha, uy",
      objBuildYear: "Obyekt qurilgan yil",
      objDatePassport: "Obyekt pasporti to'ldirilgan sana",
      objHistorical: "Obyektning tarixiy-madaniy ahamiyatga ega ekanligi",
      objBuildCount: "Bino va inshootlar soni",
      createUser: "Foydalanuvchi yaratish",
      have: "Ega",
      notHave: "Ega emas",
      organizations: "Tashkilotlar",
      orgList: "Tashkilotlar ro'yxati",
      objCount: "Obyektlar soni",
      orgCount: "Tashkilotlar soni",
    },
  },
  ru: {
    translation: {
      lang: "Язык",
      logout: "Выйти",
      users: "Пользователи",
      objects: "Объекты",
      map: "Карта",
      settings: "Настройки",
      error: "Запрещено",
      notEntry: "У вас нет прав, чтобы зайти в систему",
      goBack: "Назад",
      cadNum: "Номер кадастра",
      orgName: "Название организации",
      buildYear: "Год стройки",
      addedBuildCount: "Количество добавленных зданий",
      buildCount: "Количество зданий",
      created: "Добавил",
      edited: "Обновил(а)",
      userInfo: "Информации пользователя",
      name: "Имя",
      lastName: "Фамилия",
      midName: "Отчество",
      phoneNumber: "Номер телефона",
      email: "Адрес электронной почты",
      close: "Закрыть",
      search: "Поиск",
      createNewUser: "Создать нового пользователя",
      login: "Логин",
      password: "Пароль",
      cancel: "Отменить",
      save: "Сохранить",
      enter: "Войти",
      continueEnter: "Войдите, чтобы продолжить",
      buildName: "Название здания",
      address: "Адрес",
      fullInfo: "Полная информация",
      copied: "Скопировано!",
      objCadNum: "Номер кадастра объекта",
      objRegion: "Регион объекта",
      objDistrict: "Район или город объекта",
      objNeighborhood: "Махалля объекта",
      objStreet: "Улица, дом объекта",
      objBuildYear: "Год строительства объекта",
      objDatePassport: "Дата заполнения паспорта объекта",
      objHistorical: "Имеет ли объект историческое-культурное значение",
      objBuildCount: "Количество зданий и строительств",
      createUser: "Создать пользователя",
      have: "Имеет",
      notHave: "Не имеет",
      organizations: "Организации",
      orgList: "Список организаций",
      objCount: "Количество объектов",
      orgCount: "Количество организаций",
    },
  },
};
