export const OBJECTS_START = "OBJECTS_START";
export const OBJECTS_SUCCESS = "OBJECTS_SUCCESS";
export const OBJECTS_FAIL = "OBJECTS_FAIL";

export const OBJECTS_START_BY_ID = "OBJECTS_START_BY_ID";
export const OBJECTS_SUCCESS_BY_ID = "OBJECTS_SUCCESS_BY_ID";
export const OBJECTS_FAIL_BY_ID = "OBJECTS_FAIL_BY_ID";
