export const ORGANIZATION_START = "ORGANIZATION_START";
export const ORGANIZATION_SUCCESS = "ORGANIZATION_SUCCESS";
export const ORGANIZATION_FAIL = "ORGANIZATION_FAIL";

export const SEARCH_ORGANIZATION_START = "SEARCH_ORGANIZATION_START";
export const SEARCH_ORGANIZATION_SUCCESS = "SEARCH_ORGANIZATION_SUCCESS";
export const SEARCH_ORGANIZATION_FAIL = "SEARCH_ORGANIZATION_FAIL";

export const ORGANIZATION_START_BY_ID = "ORGANIZATION_START_BY_ID";
export const ORGANIZATION_SUCCESS_BY_ID = "ORGANIZATION_SUCCESS_BY_ID";
export const ORGANIZATION_FAIL_BY_ID = "ORGANIZATION_FAIL_BY_ID";
