export const STATISTIC_START = "STATISTIC_START";
export const STATISTIC_SUCCESS = "STATISTIC_SUCCESS";
export const STATISTIC_DIAGRAM_SUCCESS = "STATISTIC_DIAGRAM_SUCCESS";
export const STATISTIC_FAIL = "STATISTIC_FAIL";
